// lib/mock/incident.ts

export const MOCK_INCIDENT = {
  id: "INC-2025-0942",
  title: "Lateral Movement via Compromised Web Server",
  severity: "HIGH" as const,
  status: "PENDING_APPROVAL" as const,
  confidence: 0.87,
  createdAt: "2025-09-19T09:14:00Z",
  updatedAt: "2025-09-19T09:22:00Z",
  affectedAssets: ["192.168.1.55", "192.168.1.10", "VLAN-10"],
  mitreTechniques: ["T1071.001", "T1059.001"],
  attackPhase: "C2 Establishment",
  threatActor: { group: "APT29", confidence: 0.62 },

  timeline: [
    {
      id: "t1",
      time: "09:14:03",
      type: "event",
      label: "Initial alert ingested",
      detail: "Suricata IDS flagged outbound C2 beacon from 192.168.1.55 → 45.33.32.156:443",
    },
    {
      id: "t2",
      time: "09:14:05",
      type: "event",
      label: "Event correlated",
      detail: "Triage agent grouped 3 related events (EVT-001, EVT-002, EVT-003) into single incident",
    },
    {
      id: "t3",
      time: "09:14:08",
      type: "agent",
      label: "Triage Agent",
      detail: "Classified as HIGH / lateral_movement. Confidence 0.87. Routing: full_pipeline.",
      agentId: "triage",
      status: "complete",
    },
    {
      id: "t4",
      time: "09:14:15",
      type: "agent",
      label: "Threat Intel Agent",
      detail: "IOC 45.33.32.156 matched AbuseIPDB (Cobalt Strike C2, conf 0.95). CVE-2024-21762 mapped. ATT&CK: T1071.001, T1059.001.",
      agentId: "threat-intel",
      status: "complete",
    },
    {
      id: "t5",
      time: "09:14:29",
      type: "agent",
      label: "Attack Analyzer Agent",
      detail: "Attack path: Web Server → AD Controller. Blast radius: 4 assets, 2 critical. Predicted next: credential_dumping, ransomware_staging.",
      agentId: "attack-analyzer",
      status: "complete",
    },
    {
      id: "t6",
      time: "09:14:41",
      type: "agent",
      label: "Containment Planner Agent",
      detail: "Generated 2 candidate plans. PLAN-A (Surgical Isolation, RES 0.88), PLAN-B (Full Segment Isolation, RES 0.91).",
      agentId: "containment-planner",
      status: "complete",
    },
    {
      id: "t7",
      time: "09:14:55",
      type: "agent",
      label: "Compliance Agent",
      detail: "PLAN-A approved. GDPR 72h notification obligation flagged. No blocking compliance issues.",
      agentId: "compliance",
      status: "complete",
    },
    {
      id: "t8",
      time: "09:15:01",
      type: "gate",
      label: "Decision Gate — Awaiting Human Approval",
      detail: "Severity HIGH: confidence 0.87 below auto-execute threshold (0.92). Operator review required.",
      agentId: "gate",
      status: "pending",
    },
  ],

  agentChain: [
    {
      id: "triage",
      name: "Triage Agent",
      status: "complete" as const,
      duration: "3s",
      reasoning: [
        "Ingested 3 raw events from Suricata and Wazuh within the same 15-minute correlation window.",
        "Fingerprint hash matched lateral movement tactic profile (source IP subnet + PowerShell execution IOC).",
        "Asset 192.168.1.55 is classified CRITICAL (Web Server, internet-facing) in CMDB.",
        "Severity scored HIGH. Confidence 0.87. Routed to full pipeline.",
      ],
      output: { severity: "HIGH", incident_type: "lateral_movement", confidence: 0.87, routing: "full_pipeline" },
    },
    {
      id: "threat-intel",
      name: "Threat Intel Agent",
      status: "complete" as const,
      duration: "7s",
      reasoning: [
        "IOC lookup: 45.33.32.156 found in AbuseIPDB with confidence 0.95, tagged C2 / Cobalt Strike.",
        "CVE-2024-21762 (Fortinet FortiOS auth bypass) detected on target asset.",
        "Semantic vector search matched APT29 tradecraft corpus with 0.62 similarity (PowerShell via WMIC, Cobalt Strike beacon).",
        "MITRE techniques T1071.001 (Application Layer Protocol) and T1059.001 (PowerShell) confirmed.",
      ],
      output: {
        ioc_matches: [{ ioc: "45.33.32.156", source: "AbuseIPDB", confidence: 0.95 }],
        cve_matches: ["CVE-2024-21762"],
        threat_actor_hypothesis: { group: "APT29", confidence: 0.62 },
      },
    },
    {
      id: "attack-analyzer",
      name: "Attack Analyzer Agent",
      status: "complete" as const,
      duration: "14s",
      reasoning: [
        "Graph traversal from 192.168.1.55 at depth 3 identified path to AD Controller (192.168.1.10).",
        "Blast radius: 4 assets reachable, 2 critical (AD Controller + Finance DB).",
        "Estimated data exposure: 120 GB based on Finance DB classification.",
        "Predicted next TTPs: credential_dumping (T1003), ransomware_staging (T1486). High confidence given APT29 attribution.",
      ],
      output: {
        blast_radius: { affected_assets: 4, critical_assets_at_risk: ["AD Controller", "Finance DB"] },
        business_impact_score: 8.4,
        predicted_next_moves: ["credential_dumping", "ransomware_staging"],
      },
    },
    {
      id: "containment-planner",
      name: "Containment Planner Agent",
      status: "complete" as const,
      duration: "12s",
      reasoning: [
        "Retrieved 4 matching playbooks for lateral_movement + C2_establishment tactic pair.",
        "Generated PLAN-A (surgical): firewall block C2 IP + quarantine host + force password reset. Disruption: LOW.",
        "Generated PLAN-B (aggressive): full VLAN-10 isolation. Disruption: HIGH. Containment certainty: 0.99.",
        "Digital twin simulation run for both plans. PLAN-A RES: 0.88. PLAN-B RES: 0.91.",
      ],
      output: { candidate_plans: 2, recommended: "PLAN-A", simulation_completed: true },
    },
    {
      id: "compliance",
      name: "Compliance Agent",
      status: "complete" as const,
      duration: "6s",
      reasoning: [
        "PLAN-A reviewed against active frameworks: GDPR, ISO 27001.",
        "No blocking compliance violations detected in PLAN-A actions.",
        "GDPR Article 33: breach notification obligation triggered — 72h window to notify DPA starts now.",
        "PLAN-A approved. Compliance cleared for execution pending operator gate.",
      ],
      output: { recommended_plan: "PLAN-A", compliance_flags: 0, reporting_obligations: 1 },
    },
  ],

  responsePlans: [
    {
      id: "PLAN-A",
      label: "Surgical Isolation",
      recommended: true,
      res: 0.88,
      containmentProb: 0.88,
      disruption: "LOW" as const,
      speed: "Fast",
      simulationScore: 88,
      actions: [
        { type: "firewall_block", target: "45.33.32.156", detail: "Block egress to C2 IP" },
        { type: "quarantine_host", target: "192.168.1.55", detail: "Isolate Web Server from network" },
        { type: "force_password_reset", target: "user:jsmith", detail: "Reset compromised credentials" },
      ],
      complianceStatus: "approved",
    },
    {
      id: "PLAN-B",
      label: "Full Segment Isolation",
      recommended: false,
      res: 0.91,
      containmentProb: 0.99,
      disruption: "HIGH" as const,
      speed: "Immediate",
      simulationScore: 91,
      actions: [
        { type: "isolate_vlan", target: "VLAN-10", detail: "Isolate entire VLAN-10 segment" },
      ],
      complianceStatus: "approved",
    },
  ],

  approvalDeadline: new Date(Date.now() + 4 * 60 * 1000).toISOString(), // 4 minutes from now
};